name: Set Version and Tag Plugins

on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: 'The release version (e.g., 0.21.0)'
        required: true
        type: string
      dryRun:
        description: 'Use DRY_RUN mode'
        required: false
        default: 'false'
jobs:
  tag:
    name: Release plugins
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Get Plugins List
      - name: Get Plugins List
        uses: ./.github/actions/plugins-list
        id: plugins-list
        with:
          plugin-version: 'LATEST'

      - name: 'Configure Git'
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      # Execute
      - name: Set Version and Tag Plugins
        if: ${{ github.event.inputs.dryRun == 'false' }}
        env:
          GITHUB_PAT: ${{ secrets.GH_PERSONAL_TOKEN }}
        run: |
          chmod +x ./dev-tools/setversion-tag-plugins.sh;
          
          ./dev-tools/setversion-tag-plugins.sh \
          --release-version=${{github.event.inputs.releaseVersion}} \
          --yes \
           ${{ steps.plugins-list.outputs.repositories }}

      - name: Set Version and Tag Plugins (DRY_RUN)
        if: ${{ github.event.inputs.dryRun == 'true' }}
        env:
          GITHUB_PAT: ${{ secrets.GH_PERSONAL_TOKEN }}
        run: |
          chmod +x ./dev-tools/setversion-tag-plugins.sh;
          
          ./dev-tools/setversion-tag-plugins.sh \
          --release-version=${{github.event.inputs.releaseVersion}} \
          --dry-run \
          --yes \
          ${{ steps.plugins-list.outputs.repositories }}