name: Publish - Docker

on:
  workflow_dispatch:
    inputs:
      plugin-version:
        description: "Kestra version"
        default: 'LATEST'
        required: false
        type: string
  workflow_call:
    inputs:
      plugin-version:
        description: "Kestra version"
        default: 'LATEST'
        required: false
        type: string
    secrets:
      DOCKERHUB_USERNAME:
        description: "The Dockerhub username."
        required: true
      DOCKERHUB_PASSWORD:
        description: "The Dockerhub password."
        required: true

jobs:
  build-artifacts:
    name: Build - Artifacts
    uses: ./.github/workflows/workflow-build-artifacts.yml
    with:
      plugin-version: ${{ github.event.inputs.plugin-version != null && github.event.inputs.plugin-version || 'LATEST' }}

  publish:
    name: Publish - Docker
    needs: build-artifacts
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - tag: ${{ needs.build-artifacts.outputs.docker-tag }}-no-plugins
            packages: ""
            python-libraries: ""

          - tag: ${{ needs.build-artifacts.outputs.docker-tag }}
            plugins: ${{ needs.build-artifacts.outputs.plugins }}
            packages: python3 python3-venv python-is-python3 python3-pip nodejs npm curl zip unzip
            python-libraries: kestra
    steps:
      - name: Checkout - Current ref
        uses: actions/checkout@v4

      # Docker setup
      - name: Docker - Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Docker - Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Docker Login
      - name: Docker - Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # Vars
      - name: Docker - Set image name
        shell: bash
        id: vars
        run: |
          TAG=${GITHUB_REF#refs/*/}
          if [[ $TAG = "master" || $TAG == v* ]]; then
            echo "plugins=${{ matrix.image.plugins }}" >> $GITHUB_OUTPUT
          else
            echo "plugins=--repositories=https://s01.oss.sonatype.org/content/repositories/snapshots ${{ matrix.image.plugins }}" >> $GITHUB_OUTPUT
          fi

      # Build Docker Image
      - name: Artifacts - Download executable
        uses: actions/download-artifact@v4
        with:
          name: exe
          path: build/executable

      - name: Docker - Copy exe to image
        shell: bash
        run: |
          cp build/executable/* docker/app/kestra && chmod +x docker/app/kestra

      - name: Docker - Fix Qemu
        shell: bash
        run: |
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes -c yes

      # Docker Build and push
      - name: Docker - Build image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: kestra/kestra:${{ matrix.image.tag }}
          platforms: linux/amd64,linux/arm64
          build-args: |
            KESTRA_PLUGINS=${{ steps.vars.outputs.plugins }}
            APT_PACKAGES=${{ matrix.image.packages }}
            PYTHON_LIBRARIES=${{ matrix.image.python-libraries }}
