name: Release

on:
  workflow_dispatch:
    inputs:
      plugin-version:
        description: "Kestra version"
        default: 'LATEST'
        required: false
        type: string
  workflow_call:
    inputs:
      plugin-version:
        description: "Kestra version"
        default: 'LATEST'
        required: false
        type: string
    secrets:
      DOCKERHUB_USERNAME:
        description: "The Dockerhub username."
        required: true
      DOCKERHUB_PASSWORD:
        description: "The Dockerhub password."
        required: true
      SONATYPE_USER:
        description: "The Sonatype username."
        required: true
      SONATYPE_PASSWORD:
        description: "The Sonatype password."
        required: true
      SONATYPE_GPG_KEYID:
        description: "The Sonatype GPG key id."
        required: true
      SONATYPE_GPG_PASSWORD:
        description: "The Sonatype GPG password."
        required: true
      SONATYPE_GPG_FILE:
        description: "The Sonatype GPG file."
        required: true
jobs:
  Docker:
    name: Publish Docker
    uses: ./.github/workflows/workflow-publish-docker.yml
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

  Maven:
    name: Publish Maven
    uses: ./.github/workflows/workflow-publish-maven.yml
    secrets:
      SONATYPE_USER: ${{ secrets.SONATYPE_USER }}
      SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
      SONATYPE_GPG_KEYID: ${{ secrets.SONATYPE_GPG_KEYID }}
      SONATYPE_GPG_PASSWORD: ${{ secrets.SONATYPE_GPG_PASSWORD }}
      SONATYPE_GPG_FILE: ${{ secrets.SONATYPE_GPG_FILE }}

  Github:
    name: Github Release
    if: startsWith(github.ref, 'refs/tags/v')
    uses: ./.github/workflows/workflow-github-release.yml
    secrets:
      GH_PERSONAL_TOKEN: ${{ secrets.GH_PERSONAL_TOKEN }}